import { PropsWithChildren, ReactNode } from "react";

import type { Metadata } from "next";
import { Amiri_Quran, Vazirmatn } from "next/font/google";

import "./globals.css";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
});

const amiriQuran = Amiri_Quran({
  variable: "--font-amiri-quran",
  subsets: ["arabic"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = PropsWithChildren;

export default function RootLayout({ children }: Props): ReactNode {
  return (
    <html lang="en">
      <body className={`${vazirmatn.variable} ${amiriQuran.variable}`}>
        {children}
      </body>
    </html>
  );
}
