name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-nextjs.yml@master
    with:
      process-name: islam
      port: 3014
    secrets: inherit
